package manager.system;

public abstract class SMParm {
	public final static String OP = "op";
	public final static String NAME = "name";
	public final static String ACCOUNT = "account";
	public final static String ACCOUNT_PWD = "account_pwd";
	public final static String EMAIL = "email";
	public final static String SIGN_IN_METHOD = "sign_in_method";
	public final static String METHOD = "method";
	public final static String TEL = "tel";
	public final static String TEL_VERIFY_CODE = "tel_verify_code";
	public final static String USER_TOKEN = "user_token";
	public final static String TEMP_USER_ID = "temp_user_id";
	public final static String FOR_EMAIL = "for_email";
	public final static String OLD_YZM = "old_yzm";
	public final static String X = "x";
	public final static String IMG_SRC = "img_src";
	public final static String VAL = "val";
	public final static String VERIFY_SRC = "verify_src";
	public final static String VERIFY_CODE = "verify_code";
	public final static String PWD = "pwd";
	public final static String RESET_PWD_VAL = "reset_pwd_val";
	public final static String FIELD = "field";
	public final static String NICK_NAME = "nick_name";
	public final static String GENDER = "gender";
	public final static String EMAIL_VERIFY_CODE ="email_verify_code";
	public final static String GROUP_ID = "group_id";
	public final static String PERMS = "perms";
	public final static String PLAN_ID = "plan_id";
	public final static String TAGS = "tags";
	public final static String FOLD = "fold";
	public final static String TARGET_PLAN_ID = "target_plan_id";
	public final static String TEMPLE_PLAN_ID = "temple_plan_id";
	public final static String ID = "id";
	public final static String IDS = "ids";
	public final static String BOOK_ID = "book_id";
	public final static String NOTE_ID = "note_id";
	public final static String CONTENT = "content";
	public final static String WITH_TODOS = "with_todos";
	public final static String IMPORTANT = "important";
	
	public final static String TARGET_ID = "target_id";
	public final static String NOTES_SEQ = "notes_seq";
	
	public final static String CAT_NAME= "cat_name";
	public final static String NOTE = "note";
	public final static String SRC_NOTE_ID = "src_note_id";
	public final static String LABEL = "label";
	public final static String CAT_TYPE = "cat_type";
	public final static String FATHER_ID = "father_id";
	public final static String MAPPING_VAL = "mapping_val";
	public final static String ITEM_ID = "item_id";
	public final static String START_DATE = "start_date";
	public final static String END_DATE = "end_date";
	public final static String RECALCULATE_STATE = "recalculate_state";
	public final static String STATE = "state";
	public final static String WS_ID = "ws_id";
	public final static String DATA = "data";
	public final static String WS_IDS = "ws_ids";
	public final static String HIDDEN = "hidden";
	public final static String PAGE = "page";
	public final static String DATE = "date";
	public final static String PLAN_ITEM_ID = "plan_item_id";
	public final static String WORK_ITEM_ID = "work_item_id";
	public final static String MOOD = "mood";
	public final static String START_TIME = "start_time";
	public final static String END_TIME = "end_time";
	public final static String FOR_ADD = "for_add";
	public final static String PDF = "pdf";
	public final static String STYLE = "style";
	public final static String SETTING = "setting";
	public final static String PLAN_SETTING = "plan_setting";
	public final static String SEQ_WEIGHT = "seq_weight";
	
	public final static String TOOL = "tool";
}
