spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scientific_manager
    username: root
    password: Expensivewin110

logging:
  level:
    org:
#      springframework: DEBUG
#自定义
hibernate:
  showSQL: true