spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scientific_manager
    username: root
    password: new_password

file:
  external:
    root: D:\Life\selfm

logging:
  level:
    org:
#      springframework: DEBUG
#自定义
hibernate:
  showSQL: true

elasticsearch:
  username: elastic
  password: Ff9T*EC5HmBchAz5=Pb5
  url: https://localhost:9200
  p12path: E:\elasticsearch-8.14.3-windows-x86_64\elasticsearch-8.14.3\config\certs\http.p12
