# 应用程序配置
spring:
  profiles:
    active: dev
  application:
    name: self_manager
server:
  error:
    include-exception: true
    include-message: always
  port: 8080

# 日志配置示例
logging:
  level:
    root: INFO
    manager: INFO

# 其他自定义配置
custom:
  property1: value1
  property2: value2

lock:
  expirationCheckCron: 0/30 * * * * ?
  expirationSeconds: 60