# 应用程序配置
spring:
  profiles:
    active: dev
  application:
    name: self_manager
server:
  error:
    include-exception: true
    include-message: always
  port: 8080

# 日志配置示例
logging:
  level:
    root: INFO
    manager: INFO

cache:
  common:
    max-size-in-m: 1024
    expiration-of-min: 10

  temp:
    max-size-in-m: 500
    expiration-of-min: 15
  perms:
    max-num: 100000

  temp-users:
    max-num: 100000

  worksheets:
    max-num: 5000

lock:
  expirationCheckCron: 0/30 * * * * ?
  expirationSeconds: 60